# Generated by Django 3.2.9 on 2021-11-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='type',
            field=models.CharField(default='Cotton Swabs', max_length=50),
            preserve_default=False,
        ),
    ]
