# Generated by Django 3.2.9 on 2021-11-22 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_inventoryitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='estimated_need',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='estimated_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='usage_rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='cost',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='rush',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='time_taken',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
