# Generated by Django 3.2.9 on 2021-11-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delete_ordersample'),
        ('laboratory', '0003_auto_20211122_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='lab_personel',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='testsample',
            name='lab_sample_id',
        ),
        migrations.RemoveField(
            model_name='testsample',
            name='test',
        ),
        migrations.DeleteModel(
            name='LabSample',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
        migrations.DeleteModel(
            name='TestSample',
        ),
    ]
