# Generated by Django 3.2.11 on 2022-02-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_auto_20211130_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='sample_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
