# Generated by Django 3.2.12 on 2022-02-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
