# Generated by Django 3.2.12 on 2022-02-15 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_remove_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='limit',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
