# Generated by Django 3.2.12 on 2022-02-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_alter_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='limit',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
