# Generated by Django 3.2.12 on 2022-02-18 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_test_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
