# Generated by Django 3.2.12 on 2022-02-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_inventoryitem_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('Solvent', 'Chemical - Solvent'), ('Organic', 'Chemical - Organic'), ('Inorganic', 'Chemical - Inorganic'), ('Liquid', 'Liquid'), ('Standard', 'Standard'), ('Consumable', 'Consumable'), ('Glassware', 'Glassware')], default='Solvent', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Received', 'Received'), ('Shipped', 'Shipped'), ('Arrived', 'Arrived'), ('Completed', 'Completed')], default='Ordered', max_length=10),
        ),
    ]
