# Generated by Django 3.2.12 on 2022-03-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_auto_20220218_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='catalog_number',
            field=models.CharField(default='0000-00', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_automatically',
            field=models.BooleanField(default=False),
        ),
    ]
