# Generated by Django 3.2.12 on 2022-03-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0012_auto_20220311_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_discontinued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_reorder_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purity',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='total_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='vendor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='usage_rate',
            field=models.IntegerField(default=0),
        ),
    ]
