# Generated by Django 3.2.12 on 2022-03-12 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0013_auto_20220311_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='last_ordered',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
