# Generated by Django 3.2.12 on 2022-03-12 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0015_alter_inventoryitem_last_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_ordered',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 19, 17, 14, 920925)),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Received', 'Received'), ('Shipped', 'Shipped'), ('Arrived', 'Arrived'), ('Completed', 'Completed'), ('Out of Stock', 'Out of Stock')], default='Ordered', max_length=20),
        ),
    ]
