# Generated by Django 3.2.12 on 2022-03-14 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0021_alter_inventoryitem_last_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_ordered',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 16, 29, 26, 126274)),
        ),
    ]
