# Generated by Django 3.2.12 on 2022-03-20 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0022_alter_inventoryitem_last_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_ordered',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 21, 16, 39, 856263)),
        ),
    ]
