# Generated by Django 3.2.12 on 2022-03-20 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0023_alter_inventoryitem_last_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_ordered',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 21, 17, 47, 95336)),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
