# Generated by Django 3.2.12 on 2022-04-02 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0024_auto_20220319_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_ordered',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 10, 40, 50, 713438)),
        ),
    ]
