# Generated by Django 3.2.9 on 2021-11-30 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_client_account_number'),
        ('orders', '0005_delete_ordersample'),
        ('laboratory', '0004_auto_20211130_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.location')),
            ],
        ),
        migrations.CreateModel(
            name='TestSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoryOrders.labsample')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=200)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoryOrders.testsample')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=100)),
                ('sample_form', models.CharField(max_length=100)),
                ('sop_number', models.CharField(max_length=100)),
                ('lab_personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.labworker')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoryOrders.sample')),
            ],
        ),
        migrations.AddField(
            model_name='labsample',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoryOrders.sample'),
        ),
    ]
