# Generated by Django 3.2.12 on 2022-02-10 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryOrders', '0003_auto_20220129_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoryOrders.sample')),
            ],
        ),
    ]
