# Generated by Django 3.2.12 on 2022-02-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_account_number'),
        ('laboratoryOrders', '0003_auto_20220129_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labsample',
            old_name='lab_location',
            new_name='location',
        ),
        migrations.CreateModel(
            name='SampleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.IntegerField()),
                ('package_intact', models.BooleanField()),
                ('material_intact', models.BooleanField()),
                ('inspection_pass', models.BooleanField()),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.labworker')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoryOrders.sample')),
            ],
        ),
    ]
