# Generated by Django 3.2.12 on 2022-02-10 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratoryOrders', '0004_auto_20220209_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleinspection',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
