# Generated by Django 3.2.12 on 2022-02-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_account_number'),
        ('laboratoryOrders', '0005_alter_sampleinspection_inspector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='lab_personel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.labworker'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_form',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sop_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
