# Generated by Django 3.2.12 on 2022-02-10 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryOrders', '0005_alter_inspection_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laboratoryOrders.sample'),
        ),
    ]
