# Generated by Django 3.2.12 on 2022-02-16 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_invoice'),
        ('laboratory', '0008_test_limit'),
        ('laboratoryOrders', '0006_internalreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.location')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoryOrders.internalreport')),
            ],
        ),
    ]
