# Generated by Django 3.2.12 on 2022-02-18 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryOrders', '0007_internalreport_orderreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='date_entry',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='pass_fail',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
