# Generated by Django 3.2.12 on 2022-02-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryOrders', '0008_auto_20220218_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='date_entry',
        ),
    ]
