# Generated by Django 3.2.12 on 2022-02-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryOrders', '0010_testresult_date_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalreport',
            name='created_at',
            field=models.DateField(),
        ),
    ]
