# Generated by Django 3.2.12 on 2022-02-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryOrders', '0011_alter_internalreport_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalreport',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
