version: "3.3"

services:
  db-postgres:
    container_name: lims_db_server_postgres
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    user: root
    volumes:
      - ./db-postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d lims_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: ./web
    volumes:
      - ./web:/src
    command: bash -c "
        python manage.py migrate
        && python manage.py shell < src/delete_content_type.py
        && python manage.py loaddata datadump.json
        && python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      db-postgres:
        condition: service_healthy
    container_name: lims_web_server
    env_file:
      - ./.env

