version: "3.3"

services:
  web:
    build: ./web
    volumes:
      - ./web:/src
    command: bash -c "
        python manage.py makemigrations
        && python manage.py migrate
        && python manage.py shell < src/delete_content_type.py
        && python manage.py loaddata datadump.json
        && python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    links:
      - db-postgres
    depends_on:
      - db-postgres
    container_name: lims_web_server
    env_file:
      - ./.env

  db-postgres:
    container_name: lims_db_server_postgres
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./db-postgres/data:/var/lib/postgresql/data

