# Generated by Django 3.2.9 on 2021-11-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211122_0554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderSample',
        ),
    ]
