# Generated by Django 3.2.9 on 2021-12-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delete_ordersample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='testpackage',
            name='test',
        ),
        migrations.DeleteModel(
            name='OrderTest',
        ),
        migrations.DeleteModel(
            name='TestPackage',
        ),
    ]
