# Generated by Django 3.2.12 on 2022-04-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220218_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-submission_date']},
        ),
    ]
